//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyChatRoom.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public partial class Message
    {
        public int Id { get; set; }
        public string text { get; set; }
        public Nullable<int> from_id { get; set; }
        public Nullable<int> to_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public string len { get; set; }
        public System.DateTime CreateAt { get; set; }
        public List<int> readIds
        {
            set
            {
                readIds = value;
            }
            get
            {
                List<int> users = new List<int>();
                var context = new MyChatRoomEntities1();
                foreach (var message_read in context.MessageRead.Where(mr => mr.MessageId == this.Id))
                {
                    users.Add(message_read.UserId);
                };
                return users;
            }
        }
        public string CreateAtParse
        {
            set
            {
                CreateAtParse = value;
            }
            get
            {
                return this.CreateAt.ToString();
            }
        }

    }
}
